version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./api
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./api/.env

  frontend:
    build: ./front
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data: