/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminEquipmentDashboard: typeof import('./src/components/admin/AdminEquipmentDashboard.vue')['default']
    AdminRequestDashboard: typeof import('./src/components/admin/AdminRequestDashboard.vue')['default']
    CustomerDashboard: typeof import('./src/components/customer/CustomerDashboard.vue')['default']
    ForgotPassword: typeof import('./src/components/ForgotPassword.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
